//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medewerker
    {
        public int medewerkerscode { get; set; }
        public string voorletters { get; set; }
        public string tussenvoegsel { get; set; }
        public string achternaam { get; set; }
        public string voornaam { get; set; }
        public string email { get; set; }
        public string wachtwoord { get; set; }
    }
}
