//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.voorraad = new HashSet<voorraad>();
        }
    
        public int productcode { get; set; }
        public string product1 { get; set; }
        public Nullable<int> fabriekscode { get; set; }
        public string type { get; set; }
        public Nullable<decimal> inkoopprijs { get; set; }
        public Nullable<decimal> verkoopprijs { get; set; }
        public int fabriek_fabriekscode { get; set; }
    
        public virtual fabriek fabriek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voorraad> voorraad { get; set; }
    }
}
