//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voorraad
    {
        public Nullable<int> locatiecode { get; set; }
        public Nullable<int> productcde { get; set; }
        public Nullable<int> aantal { get; set; }
        public int locatie_locatiecode { get; set; }
        public int product_productcode { get; set; }
    
        public virtual locatie locatie { get; set; }
        public virtual product product { get; set; }
    }
}
